<?php

namespace Wcs\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    public function voteReponsesForbiddenByUserAndByQuestion($idUser, $idQuestion){

        $query = $this->getEntityManager()->createQueryBuilder();
            $query->select('IDENTITY(v.reponse)');
            $query->from('WcsPlatformBundle:Vote', 'v');
            $query->where('IDENTITY(v.user) = :idUser');
            $query->andWhere('IDENTITY(v.question) = :idQuestion');
            $query->setParameters(array(
                'idUser' => $idUser,
                'idQuestion' => $idQuestion
            ));
        return $query->getQuery()->getResult();
    }
}
