wcs_platform_questions:
    resource: "@WcsPlatformBundle/Resources/config/routing/questions.yml"
    prefix:   /questions

wcs_platform_homepage:
    path:     /
    defaults: { _controller: WcsPlatformBundle:Questions:index }

wcs_platform_reponses:
    resource: "@WcsPlatformBundle/Resources/config/routing/reponses.yml"
    prefix:   /reponses