wcs_platform_questions:
    resource: "@WcsPlatformBundle/Resources/config/routing/questions.yml"
    prefix:   /questions
<<<<<<< Updated upstream
=======

wcs_platform_homepage:
    path:     /
    defaults: { _controller: WcsPlatformBundle:Questions:index }
>>>>>>> Stashed changes

wcs_platform_homepage:
    path:     /
    defaults: { _controller: WcsPlatformBundle:Questions:index }

wcs_platform_homepage:
    path:     /
    defaults: { _controller: WcsPlatformBundle:Accueil:index }